### Obtener todos los estudiantes
### Obtener todos los estudiantes
GET http://localhost:8080/api/estudiante
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJyb2xlcyI6WyJST0xFX1BST0ZFU09SIiwiUk9MRV9BRE1JTiJdLCJzdWIiOiJhbmRyZXMucm9qYXNAdW5pdmVyc2lkYWQuY29tIiwiaWF0IjoxNzUyMzc4MzM0LCJleHAiOjE3NTI0NjQ3MzR9.GUozM_Obfil9F2u6YCJ3ADaHVPL1Y1t2_z-hpsr2-RrDSx9cfDEKtJ4Eqe06EaGe
Content-Type: application/json

### Obtener estudiante por ID
GET http://localhost:8080/api/estudiante/1
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJyb2xlcyI6WyJST0xFX1BST0ZFU09SIiwiUk9MRV9BRE1JTiJdLCJzdWIiOiJhbmRyZXMucm9qYXNAdW5pdmVyc2lkYWQuY29tIiwiaWF0IjoxNzUyMzc4MzM0LCJleHAiOjE3NTI0NjQ3MzR9.GUozM_Obfil9F2u6YCJ3ADaHVPL1Y1t2_z-hpsr2-RrDSx9cfDEKtJ4Eqe06EaGe
Content-Type: application/json

### Crear nuevo estudiante
POST http://localhost:8080/api/estudiante
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJyb2xlcyI6WyJST0xFX1BST0ZFU09SIiwiUk9MRV9BRE1JTiJdLCJzdWIiOiJhbmRyZXMucm9qYXNAdW5pdmVyc2lkYWQuY29tIiwiaWF0IjoxNzUyMzc4MzM0LCJleHAiOjE3NTI0NjQ3MzR9.GUozM_Obfil9F2u6YCJ3ADaHVPL1Y1t2_z-hpsr2-RrDSx9cfDEKtJ4Eqe06EaGe

{
    "name": "Juan Pérez",
    "last_name": "Pérez",
    "email": "juan.perez@universidad.com",
    "phone": "3001234567",
    "address": "Calle 123 #45-67, Bogotá",
    "student_Number": "2024001234",
    "password": "$2a$12$O5hsMe6Q4awpciX3uAyaBOeDuyryTidudNJssHUEI2mNGBKfKCEoq"
}

### Actualizar estudiante
PUT http://localhost:8080/api/estudiante/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJyb2xlcyI6WyJST0xFX1BST0ZFU09SIiwiUk9MRV9BRE1JTiJdLCJzdWIiOiJhbmRyZXMucm9qYXNAdW5pdmVyc2lkYWQuY29tIiwiaWF0IjoxNzUyMzc4MzM0LCJleHAiOjE3NTI0NjQ3MzR9.GUozM_Obfil9F2u6YCJ3ADaHVPL1Y1t2_z-hpsr2-RrDSx9cfDEKtJ4Eqe06EaGe

{
    "name": "Juan Carlos",
    "last_name": "Pérez rojas",
    "email": "juan.perez@universidad.com",
    "phone": "3001234568",
    "address": "Calle 124 #46-68, Bogotá",
    "student_Number": "2024001234"
}

### Eliminar estudiante
DELETE http://localhost:8080/api/estudiante/1

### Buscar estudiantes por nombre
GET http://localhost:8080/api/estudiante/buscar?b=Juan
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJyb2xlcyI6WyJST0xFX1BST0ZFU09SIiwiUk9MRV9BRE1JTiJdLCJzdWIiOiJhbmRyZXMucm9qYXNAdW5pdmVyc2lkYWQuY29tIiwiaWF0IjoxNzUyMzc4MzM0LCJleHAiOjE3NTI0NjQ3MzR9.GUozM_Obfil9F2u6YCJ3ADaHVPL1Y1t2_z-hpsr2-RrDSx9cfDEKtJ4Eqe06EaGe
Content-Type: application/json


